name: RestoreChunk
version: '${version}'
main: dev.warriorrr.restorechunk.RestoreChunkPlugin
api-version: '1.21'
load: STARTUP
authors: [ Warriorrr ]
folia-supported: true

commands:
  restorechunk:
    usage: "Restores a chunk to its previous state."
    permission: restorechunk.command.restorechunk

permissions:
  restorechunk.command.*:
    default: op
    children:
      restorechunk.command.restorechunk: true
